//! The [[usage history]] domain: the retained, append-over-time record of
//! each account's past quota readings, coalesced at display granularity,
//! bounded by a [[retention policy]], and persisted to one whole-file JSON
//! document per host.
//!
//! This module is deliberately a third corruption policy, distinct from its
//! two neighbours in this crate:
//!
//! - `crate::shared_config` (user-authored, the only copy, names unenumerable
//!   secrets) is **kept and blocks saves** when unreadable;
//! - `crate::snapshots::SnapshotStore` (wholly derived, regenerated by the
//!   next refresh) is **discarded to empty** when unreadable;
//! - usage history is *valuable but reconstructible-going-forward and holds
//!   no secrets*: the readings took time to accumulate and cannot be refetched
//!   from the providers, but nothing security-relevant lives here and the next
//!   observation is always around the corner. So an unreadable/unparseable
//!   `usage-history.json` is **renamed aside to `usage-history.json.corrupt`
//!   (then `.corrupt.2`, …) and a fresh empty history starts immediately** —
//!   the bytes are never deleted, and the fault never blocks a refresh or a
//!   save the way a corrupt config must.
//!
//! Recording is **coalesced**: a history point is appended for an account only
//! when its observation differs from that account's last recorded point at
//! display granularity (rounded integer percentage per window, credits balance
//! to a fixed precision, failure state present/absent). A steady-state refresh
//! writes nothing.
//!
//! [[Cleaning preview]] is pure: [`UsageHistory::preview_prune`] reports
//! exactly what [`UsageHistory::prune`] would remove — same points, same
//! count, same bytes — because both are driven by one shared partition
//! function. The confirmation UI shows the preview; confirming applies the
//! very decision it showed.
//!
//! [`UsageHistory::capture`] is the one host-side seam: every host (desktop
//! poller, Android foreground refresh, Android background worker) records one
//! `RefreshOutcome` through it, so every host records the same thing the same
//! way. All reads and writes coordinate through the snapshot store lock
//! (`crate::snapshots::store_lock`), the same lock configuration saves take,
//! and every write is an atomic temp-then-rename so a torn write can never
//! corrupt an existing history.
//!
//! [[usage history]]: ../../CONTEXT.md
//! [[retention policy]]: ../../CONTEXT.md
//! [[cleaning preview]]: ../../CONTEXT.md
//! [[history point]]: ../../CONTEXT.md
//! [[history cleaning]]: ../../CONTEXT.md

use crate::refresh::RefreshOutcome;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

/// The file the usage history is persisted to, alongside the other stores in
/// the app config directory.
const FILE_NAME: &str = "usage-history.json";

/// The unit an [[retention policy|age bound]] counts in.
///
/// [[retention policy]]: ../../CONTEXT.md
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum AgeUnit {
    #[default]
    Days,
    Weeks,
    Months,
    Years,
}

/// The [[retention policy]]: the rule bounding how much [[usage history]] is
/// kept — forever, an age bound, or a file-size bound. Part of shared
/// configuration, so its meaning is common to every platform. Default
/// [`HistoryRetention::Forever`]: an existing config that predates the field
/// keeps everything, which is also what a first run wants.
///
/// [[retention policy]]: ../../CONTEXT.md
/// [[usage history]]: ../../CONTEXT.md
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum HistoryRetention {
    /// Keep everything, never clean. The default.
    #[default]
    Forever,
    /// Keep the most recent `amount` `unit`s of history; points recorded
    /// before that age are outside the bound.
    Age { unit: AgeUnit, amount: u32 },
    /// Keep points until their serialized size would exceed `bytes`, dropping
    /// oldest first.
    FileSize { bytes: u64 },
}

/// One [[history point]]: a single coalesced observation for one account at a
/// moment — each usage window's percentage keyed by its stable `metric_id`,
/// the credits balance if the account has one, and whether the reading was a
/// failure. Window labels and credit units are display data the snapshot
/// still carries; a point keeps the quantities only, so a relabelled window
/// or a renamed unit does not fork the record.
///
/// [[history point]]: ../../CONTEXT.md
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HistoryPoint {
    pub at: DateTime<Utc>,
    /// `(metric_id, used_pct)` per usage window, in the order the snapshot
    /// reported them.
    pub windows: Vec<(String, f64)>,
    /// The credits balance, when the account reports one. An *amount* in the
    /// account's own unit — never a percentage (see CONTEXT.md "Credits").
    pub credits_balance: Option<f64>,
    /// Whether the observation failed (a fetch error was present). A failed
    /// reading may still carry the last successful figures the shared refresh
    /// preserved across the failure ([[stale reading]]); the flag is what
    /// marks the difference between "measured now" and "carried, not new".
    ///
    /// [[stale reading]]: ../../CONTEXT.md
    pub failed: bool,
}

/// The whole persisted [[usage history]] store: per-account points keyed by
/// the account's provider id (the `String` identity — there is no provider
/// enum). Each account's points are ordered oldest-first; recording and
/// pruning both preserve that order, and the chart and the age bound both
/// rely on it.
///
/// [[usage history]]: ../../CONTEXT.md
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct UsageHistory {
    /// Reserved for forward-compatible migrations. Fields are added under
    /// `#[serde(default)]`, so an older reader tolerates a newer file and a
    /// newer reader tolerates an older one.
    pub version: u32,
    /// Points per account, oldest first.
    pub accounts: BTreeMap<String, Vec<HistoryPoint>>,
}

impl Default for UsageHistory {
    fn default() -> Self {
        Self {
            version: 1,
            accounts: BTreeMap::new(),
        }
    }
}

/// The [[cleaning preview]]: exactly what a [`UsageHistory::prune`] under the
/// same policy at the same moment removes — same points, same count, same
/// bytes. Pure: computed without touching disk or mutating the store, so the
/// confirmation UI can show the figures before anything is deleted and the
/// tests can pin the preview/apply contract without I/O.
///
/// [[cleaning preview]]: ../../CONTEXT.md
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct PrunePreview {
    /// How many history points would be removed.
    pub removed_count: usize,
    /// How many serialized bytes they occupy — `Some` only for a file-size
    /// bound, where bytes are the bound itself; `None` for *forever* and age
    /// bounds, where a byte figure would be noise.
    pub removed_bytes: Option<u64>,
    /// The oldest point that would remain after cleaning (`None` when nothing
    /// remains, or the history is empty). Together with `newest_removed` this
    /// is the time span the confirmation shows.
    pub oldest_kept: Option<DateTime<Utc>>,
    /// The newest point that would be removed (`None` when nothing would be).
    pub newest_removed: Option<DateTime<Utc>>,
}

/// The serialized size of one point — the measure the file-size bound counts
/// in. Deliberately the point's own JSON, not the whole file's: the envelope
/// is near-constant overhead, and per-point measurement is what makes the
/// preview's byte figure computable without writing anything.
fn point_bytes(point: &HistoryPoint) -> u64 {
    serde_json::to_vec(point)
        .expect("history point serializes")
        .len() as u64
}

/// The display-granularity observation a point coalesces on: rounded integer
/// percentage per window, credits balance in cents, and the failure state. Two
/// observations with equal keys are the same reading as far as any screen can
/// show, so the second records nothing.
fn observation_key(point: &HistoryPoint) -> (Vec<(String, i64)>, Option<i64>, bool) {
    (
        point
            .windows
            .iter()
            .map(|(id, pct)| (id.clone(), display_pct(*pct)))
            .collect(),
        point.credits_balance.map(display_credits),
        point.failed,
    )
}

/// Rounded integer percentage — the granularity a card or a chart axis shows.
fn display_pct(pct: f64) -> i64 {
    pct.round() as i64
}

/// Credits balance at a fixed precision (cents). A balance drifting by less
/// than a displayed cent is not a change worth a history point.
fn display_credits(balance: f64) -> i64 {
    (balance * 100.0).round() as i64
}

impl UsageHistory {
    /// Append a point per account in `outcome`, but only where the observation
    /// differs from that account's last recorded point at display granularity
    /// — the [[history point]] coalescing rule. An unchanged steady-state
    /// refresh writes nothing.
    ///
    /// [[history point]]: ../../CONTEXT.md
    pub fn record(&mut self, outcome: &RefreshOutcome, now: DateTime<Utc>) {
        for snapshot in &outcome.snapshots {
            let point = HistoryPoint {
                at: now,
                windows: snapshot
                    .windows
                    .iter()
                    .map(|w| (w.metric_id.clone(), w.used_pct))
                    .collect(),
                credits_balance: snapshot.credits.as_ref().map(|c| c.balance),
                failed: snapshot.error.is_some(),
            };
            let points = self
                .accounts
                .entry(snapshot.provider_id.clone())
                .or_default();
            if points
                .last()
                .is_some_and(|last| observation_key(last) == observation_key(&point))
            {
                continue;
            }
            points.push(point);
            // Recording times are monotonic in practice (`now` never goes back
            // within a process), but a clock adjustment must not silently break
            // the oldest-first invariant the age bound and the charts rely on.
            points.sort_by_key(|p| p.at);
        }
    }

    /// Apply the [[retention policy]]: drop the points outside the active
    /// bound ([[history cleaning]]). Called after every record so steady-state
    /// history stays within policy silently; a *policy change to a tighter
    /// bound* is gated behind [`UsageHistory::preview_prune`] + confirmation
    /// by the hosts. A looser bound or *forever* removes nothing.
    ///
    /// [[retention policy]]: ../../CONTEXT.md
    /// [[history cleaning]]: ../../CONTEXT.md
    pub fn prune(&mut self, policy: &HistoryRetention, now: DateTime<Utc>) {
        let (kept, _) = self.partition(policy, now);
        self.accounts = kept;
    }

    /// The pure [[cleaning preview]]: exactly what [`UsageHistory::prune`]
    /// would remove under `policy` at `now` — no disk, no mutation.
    ///
    /// [[cleaning preview]]: ../../CONTEXT.md
    pub fn preview_prune(&self, policy: &HistoryRetention, now: DateTime<Utc>) -> PrunePreview {
        let (kept, removed) = self.partition(policy, now);
        PrunePreview {
            removed_count: removed.len(),
            removed_bytes: matches!(policy, HistoryRetention::FileSize { .. })
                .then(|| removed.iter().map(point_bytes).sum()),
            oldest_kept: kept.values().flatten().map(|p| p.at).min(),
            newest_removed: removed.iter().map(|p| p.at).max(),
        }
    }

    /// The one partition both [`prune`](Self::prune) and
    /// [`preview_prune`](Self::preview_prune) are built on — the single place
    /// the preview/apply contract lives, so they cannot drift. Returns the
    /// kept per-account points and the flat removed list.
    fn partition(
        &self,
        policy: &HistoryRetention,
        now: DateTime<Utc>,
    ) -> (BTreeMap<String, Vec<HistoryPoint>>, Vec<HistoryPoint>) {
        let mut kept: BTreeMap<String, Vec<HistoryPoint>> = BTreeMap::new();
        let mut removed: Vec<HistoryPoint> = Vec::new();
        match policy {
            HistoryRetention::Forever => {
                kept = self.accounts.clone();
            }
            HistoryRetention::Age { unit, amount } => {
                // A cutoff that cannot be computed (an overflow so large the
                // bound can never expire anything) keeps everything.
                if let Some(cutoff) = age_cutoff(now, *unit, *amount) {
                    for (id, points) in &self.accounts {
                        let (old, new): (Vec<HistoryPoint>, Vec<HistoryPoint>) =
                            points.iter().cloned().partition(|p| p.at < cutoff);
                        kept.insert(id.clone(), new);
                        removed.extend(old);
                    }
                } else {
                    kept = self.accounts.clone();
                }
            }
            HistoryRetention::FileSize { bytes } => {
                // Start whole, then drop the globally oldest point repeatedly
                // until the store measures under the bound. Ties on time are
                // broken by account id, so the outcome is deterministic.
                for (id, points) in &self.accounts {
                    kept.insert(id.clone(), points.clone());
                }
                loop {
                    let total: u64 = kept.values().flatten().map(point_bytes).sum();
                    if total <= *bytes {
                        break;
                    }
                    let Some(victim) = kept
                        .iter()
                        .min_by(|a, b| match (a.1.first(), b.1.first()) {
                            (Some(pa), Some(pb)) => pa.at.cmp(&pb.at).then_with(|| a.0.cmp(b.0)),
                            (Some(_), None) => std::cmp::Ordering::Less,
                            (None, Some(_)) => std::cmp::Ordering::Greater,
                            (None, None) => std::cmp::Ordering::Equal,
                        })
                        .map(|(id, _)| id.clone())
                    else {
                        break;
                    };
                    let points = kept.get_mut(&victim).expect("victim came from kept");
                    let dropped = points.remove(0);
                    removed.push(dropped);
                }
            }
        }
        (kept, removed)
    }

    /// Read the persisted history. A missing file is the empty history —
    /// nothing has been recorded yet. A file that exists but cannot be read
    /// or parsed follows this module's third corruption policy: the original
    /// is renamed aside to `usage-history.json.corrupt` (numbered onward) and
    /// a fresh empty history starts — never deleted in place, never blocking.
    ///
    /// Safe to call without the store lock, like `SnapshotStore::load`: saves
    /// publish by atomic rename, so a reader sees a whole file or none. The
    /// corrupt-aside rename it may perform is the documented policy, not a
    /// coordination point.
    pub fn load(dir: &Path) -> Self {
        let text = match std::fs::read_to_string(dir.join(FILE_NAME)) {
            Ok(text) => text,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Self::default(),
            // Unreadable (permissions, I/O) is the corrupt shape too: a file
            // is on disk and we cannot trust what it says.
            Err(_) => {
                rename_aside(dir);
                return Self::default();
            }
        };
        match serde_json::from_str(&text) {
            Ok(history) => history,
            Err(_) => {
                rename_aside(dir);
                Self::default()
            }
        }
    }

    /// Write the history atomically — temp file, then rename over the store —
    /// so a reader or a process killed mid-write never sees a partial JSON
    /// document. Unlike configuration this never refuses to overwrite: the
    /// corruption policy above already handles the one case that matters.
    /// Callers that can race other writers hold
    /// [`crate::snapshots::store_lock`] (see [`UsageHistory::capture`]).
    pub fn save(&self, dir: &Path) -> std::io::Result<()> {
        std::fs::create_dir_all(dir)?;
        let text = serde_json::to_string_pretty(self).expect("usage history serializes");
        let tmp = dir.join(format!("{FILE_NAME}.tmp"));
        std::fs::write(&tmp, text)?;
        std::fs::rename(tmp, dir.join(FILE_NAME))
    }

    /// The one host-side capture seam — lock, load, record, prune, save, in
    /// one critical section under the snapshot store lock. Every host records
    /// a `RefreshOutcome` through this, so desktop and Android accumulate
    /// identical history from identical outcomes. A caller treats an error as
    /// best-effort: a history-persist failure must never break the refresh
    /// that produced the outcome.
    pub fn capture(
        dir: &Path,
        outcome: &RefreshOutcome,
        policy: &HistoryRetention,
        now: DateTime<Utc>,
    ) -> std::io::Result<()> {
        let _lock = crate::snapshots::store_lock(dir)?;
        let mut history = Self::load(dir);
        history.record(outcome, now);
        history.prune(policy, now);
        history.save(dir)
    }

    /// Apply a (typically tighter) [[retention policy]] to the stored history:
    /// lock, load, preview, prune, save — returning the same figures the
    /// confirmation preview showed. The host persists the policy itself
    /// (through the configuration save) before calling this; a failure here
    /// leaves the history uncleaned, and the next record's steady-state prune
    /// converges it.
    ///
    /// [[retention policy]]: ../../CONTEXT.md
    pub fn apply_policy(
        dir: &Path,
        policy: &HistoryRetention,
        now: DateTime<Utc>,
    ) -> std::io::Result<PrunePreview> {
        let _lock = crate::snapshots::store_lock(dir)?;
        let mut history = Self::load(dir);
        let preview = history.preview_prune(policy, now);
        history.prune(policy, now);
        history.save(dir)?;
        Ok(preview)
    }
}

/// The cutoff an age bound names: points recorded before it are outside the
/// policy. `None` when the bound is too large to compute against `now` —
/// such a bound can never expire anything, so everything is kept.
fn age_cutoff(now: DateTime<Utc>, unit: AgeUnit, amount: u32) -> Option<DateTime<Utc>> {
    match unit {
        AgeUnit::Days => now.checked_sub_signed(chrono::Duration::days(i64::from(amount))),
        AgeUnit::Weeks => now.checked_sub_signed(chrono::Duration::weeks(i64::from(amount))),
        AgeUnit::Months => now.checked_sub_months(chrono::Months::new(amount)),
        // Months::new takes a u32, so a u32 year count times twelve can
        // overflow; a bound that large keeps everything.
        AgeUnit::Years => amount
            .checked_mul(12)
            .and_then(|months| now.checked_sub_months(chrono::Months::new(months))),
    }
}

/// Where an unreadable history file is kept: numbered like every other
/// kept-aside copy in this crate, so a second corruption cannot destroy the
/// first copy. The bytes are never deleted.
fn corrupt_backup_path(dir: &Path) -> std::path::PathBuf {
    let first = dir.join(format!("{FILE_NAME}.corrupt"));
    if !first.exists() {
        return first;
    }
    for n in 2u32.. {
        let candidate = dir.join(format!("{FILE_NAME}.corrupt.{n}"));
        if !candidate.exists() {
            return candidate;
        }
    }
    unreachable!("u32 exhausted while naming a history backup")
}

/// Best-effort: a rename that cannot land (the file vanished, permissions)
/// must never block the refresh that tripped over the corrupt file. Losing
/// the rename only means the next load tries again.
fn rename_aside(dir: &Path) {
    let _ = std::fs::rename(dir.join(FILE_NAME), corrupt_backup_path(dir));
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{Credits, FetchError, UsageSnapshot, UsageWindow};

    fn window(metric: &str, pct: f64) -> UsageWindow {
        UsageWindow {
            metric_id: metric.into(),
            label: metric.into(),
            used_pct: pct,
            ..Default::default()
        }
    }

    fn credits(balance: f64) -> Credits {
        Credits {
            balance,
            label: None,
            unit: "USD".into(),
            used: None,
            granted: None,
            est_tokens_remaining: None,
        }
    }

    fn ok(id: &str, pct: f64) -> UsageSnapshot {
        UsageSnapshot::ok(id, id, vec![window("five_hour", pct)], None)
    }

    fn ok_credits(id: &str, balance: f64) -> UsageSnapshot {
        UsageSnapshot::ok(id, id, vec![], Some(credits(balance)))
    }

    fn failed(id: &str) -> UsageSnapshot {
        UsageSnapshot::failed(id, id, FetchError::Network("boom".into()))
    }

    fn outcome(snapshots: Vec<UsageSnapshot>) -> RefreshOutcome {
        RefreshOutcome {
            snapshots,
            ..Default::default()
        }
    }

    fn point(at: DateTime<Utc>, pct: f64) -> HistoryPoint {
        HistoryPoint {
            at,
            windows: vec![("five_hour".into(), pct)],
            credits_balance: None,
            failed: false,
        }
    }

    fn days_before(now: DateTime<Utc>, days: u32) -> DateTime<Utc> {
        now - chrono::Duration::days(i64::from(days))
    }

    // ---- Coalescing ---------------------------------------------------------

    /// Two refreshes showing the same displayed figures record one point, not
    /// two: 42.4% and 42.49% both display as 42%.
    #[test]
    fn an_unchanged_refresh_records_no_duplicate_point() {
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.record(&outcome(vec![ok("claude", 42.4)]), now);
        history.record(
            &outcome(vec![ok("claude", 42.49)]),
            now + chrono::Duration::seconds(60),
        );
        assert_eq!(history.accounts["claude"].len(), 1);
    }

    /// A change in any displayed dimension — percentage, credits balance,
    /// failure state — appends a new point.
    #[test]
    fn a_changed_percentage_balance_or_failure_appends_a_point() {
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.record(&outcome(vec![ok("claude", 42.0)]), now);
        history.record(
            &outcome(vec![ok("claude", 43.0)]),
            now + chrono::Duration::seconds(60),
        );
        assert_eq!(history.accounts["claude"].len(), 2, "a changed percentage");

        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.record(&outcome(vec![ok_credits("openrouter", 10.004)]), now);
        history.record(
            &outcome(vec![ok_credits("openrouter", 9.99)]),
            now + chrono::Duration::seconds(60),
        );
        assert_eq!(
            history.accounts["openrouter"].len(),
            2,
            "a cent-scale balance change"
        );

        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.record(&outcome(vec![ok("claude", 42.0)]), now);
        history.record(
            &outcome(vec![failed("claude")]),
            now + chrono::Duration::seconds(60),
        );
        assert_eq!(
            history.accounts["claude"].len(),
            2,
            "a flipped failure state"
        );
        assert!(history.accounts["claude"][1].failed);
    }

    /// Two identical failures coalesce too — the failure state is part of the
    /// observation, and an outage that sits still adds nothing.
    #[test]
    fn two_identical_failures_coalesce() {
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.record(&outcome(vec![failed("claude")]), now);
        history.record(
            &outcome(vec![failed("claude")]),
            now + chrono::Duration::seconds(60),
        );
        assert_eq!(history.accounts["claude"].len(), 1);
        assert!(history.accounts["claude"][0].failed);
        assert!(history.accounts["claude"][0].windows.is_empty());
    }

    /// A stale reading (preserved figures + new error) records both truths:
    /// the figures it carried and failed=true. Accounts are keyed by their
    /// `String` provider id, multi-account included.
    #[test]
    fn a_stale_reading_records_figures_and_failure_by_account_key() {
        let now = Utc::now();
        let mut stale = ok("claude#2", 20.0);
        stale.error = Some(FetchError::Network("boom".into()));
        let mut history = UsageHistory::default();
        history.record(&outcome(vec![ok("claude#2", 20.0)]), now);
        history.record(&outcome(vec![stale]), now + chrono::Duration::seconds(60));
        let points = &history.accounts["claude#2"];
        assert_eq!(points.len(), 2);
        assert!(!points[0].failed);
        assert_eq!(points[1].windows, vec![("five_hour".into(), 20.0)]);
        assert!(points[1].failed);
    }

    // ---- Age pruning --------------------------------------------------------

    #[test]
    fn an_age_bound_drops_only_points_older_than_it() {
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.accounts.insert(
            "claude".into(),
            vec![
                point(days_before(now, 30), 10.0),
                point(days_before(now, 6), 20.0),
                point(days_before(now, 1), 30.0),
            ],
        );
        history.prune(
            &HistoryRetention::Age {
                unit: AgeUnit::Days,
                amount: 7,
            },
            now,
        );
        let kept = &history.accounts["claude"];
        assert_eq!(
            kept.iter().map(|p| p.at).collect::<Vec<_>>(),
            vec![days_before(now, 6), days_before(now, 1)],
            "oldest-first order preserved, the 30-day-old point dropped",
        );
    }

    /// A point recorded exactly at the cutoff is inside the bound (`>=`), so
    /// the boundary belongs to the kept side.
    #[test]
    fn a_point_exactly_at_the_age_cutoff_is_kept() {
        let now = Utc::now();
        let cutoff_time = days_before(now, 7);
        let mut history = UsageHistory::default();
        history.accounts.insert(
            "claude".into(),
            vec![point(cutoff_time, 10.0), point(days_before(now, 8), 20.0)],
        );
        history.prune(
            &HistoryRetention::Age {
                unit: AgeUnit::Days,
                amount: 7,
            },
            now,
        );
        assert_eq!(history.accounts["claude"].len(), 1);
        assert_eq!(history.accounts["claude"][0].at, cutoff_time);
    }

    #[test]
    fn every_age_unit_expires_against_now() {
        let now = Utc::now();
        for (unit, amount, expected_days) in [
            (AgeUnit::Days, 7, 7),
            (AgeUnit::Weeks, 2, 14),
            (AgeUnit::Months, 1, 31),
            (AgeUnit::Years, 1, 366),
        ] {
            let mut history = UsageHistory::default();
            history.accounts.insert(
                "claude".into(),
                vec![
                    point(days_before(now, expected_days + 1), 10.0),
                    point(days_before(now, expected_days - 1), 20.0),
                ],
            );
            history.prune(&HistoryRetention::Age { unit, amount }, now);
            let kept = &history.accounts["claude"];
            assert_eq!(
                kept.len(),
                1,
                "{unit:?} bound kept the wrong points ({kept:?})"
            );
            assert_eq!(kept[0].windows[0].1, 20.0);
        }
    }

    // ---- File-size pruning --------------------------------------------------

    #[test]
    fn a_file_size_bound_drops_oldest_first_until_under_it() {
        let now = Utc::now();
        let points: Vec<HistoryPoint> = (0..4)
            .map(|i| point(days_before(now, 4 - i), i as f64 * 10.0))
            .collect();
        // The bound fits exactly the newest two points.
        let bound = point_bytes(&points[2]) + point_bytes(&points[3]);
        let mut history = UsageHistory::default();
        history.accounts.insert("claude".into(), points);
        history.prune(&HistoryRetention::FileSize { bytes: bound }, now);
        let kept = &history.accounts["claude"];
        assert_eq!(kept.len(), 2, "the two newest points fit the bound");
        assert_eq!(
            kept[0].windows[0].1, 20.0,
            "the oldest points were dropped first"
        );
        assert_eq!(kept[1].windows[0].1, 30.0);
    }

    /// A bound smaller than a single point empties the store rather than
    /// keeping something it cannot afford.
    #[test]
    fn a_file_size_bound_smaller_than_one_point_empties_the_store() {
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history
            .accounts
            .insert("claude".into(), vec![point(now, 10.0)]);
        history.prune(&HistoryRetention::FileSize { bytes: 1 }, now);
        assert!(history.accounts["claude"].is_empty());
    }

    /// The size bound is global across accounts: the globally oldest point
    /// goes first, whichever account it lives under.
    #[test]
    fn a_file_size_bound_drops_the_globally_oldest_point_first() {
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history
            .accounts
            .insert("claude".into(), vec![point(days_before(now, 10), 10.0)]);
        history
            .accounts
            .insert("openrouter".into(), vec![point(days_before(now, 5), 50.0)]);
        history.prune(
            &HistoryRetention::FileSize {
                bytes: point_bytes(&point(days_before(now, 5), 50.0)),
            },
            now,
        );
        assert!(
            history.accounts["claude"].is_empty(),
            "claude's older point went first"
        );
        assert_eq!(history.accounts["openrouter"].len(), 1);
    }

    // ---- Preview == apply (the one contract Slice 2 relies on) --------------

    /// The preview reports exactly what `prune` then removes — count, bytes,
    /// and the boundary timestamps — for both bound kinds.
    #[test]
    fn preview_prune_matches_what_prune_removes() {
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.accounts.insert(
            "claude".into(),
            vec![
                point(days_before(now, 30), 10.0),
                point(days_before(now, 20), 20.0),
                point(days_before(now, 1), 30.0),
            ],
        );
        history.accounts.insert(
            "openrouter".into(),
            vec![
                point(days_before(now, 25), 50.0),
                point(days_before(now, 2), 60.0),
            ],
        );

        let policy = HistoryRetention::Age {
            unit: AgeUnit::Days,
            amount: 10,
        };
        let preview = history.preview_prune(&policy, now);
        let mut applied = history.clone();
        applied.prune(&policy, now);
        assert_eq!(
            preview.removed_count, 3,
            "claude×2 + openrouter×1 are older than 10 days"
        );
        assert_eq!(
            preview.removed_bytes, None,
            "an age bound reports no byte figure"
        );
        assert_eq!(preview.newest_removed, Some(days_before(now, 20)));
        // The oldest kept is openrouter's 2-day-old point — the min across
        // every account, not the first account's newest.
        assert_eq!(preview.oldest_kept, Some(days_before(now, 2)));
        assert_eq!(
            applied
                .accounts
                .values()
                .flatten()
                .map(|p| p.at)
                .collect::<std::collections::BTreeSet<_>>(),
            history
                .preview_prune(&policy, now)
                .oldest_kept
                .into_iter()
                .chain(applied.accounts.values().flatten().map(|p| p.at))
                .collect::<std::collections::BTreeSet<_>>(),
        );
        // Directly: what remains is exactly what the preview said would remain.
        assert_eq!(
            applied.accounts.values().flatten().count(),
            history.accounts.values().flatten().count() - preview.removed_count,
        );
    }

    #[test]
    fn preview_prune_reports_bytes_for_a_file_size_bound() {
        let now = Utc::now();
        let points: Vec<HistoryPoint> = (0..3)
            .map(|i| point(days_before(now, 3 - i), i as f64 * 10.0))
            .collect();
        let removed_expected = point_bytes(&points[0]) + point_bytes(&points[1]);
        let mut history = UsageHistory::default();
        history.accounts.insert("claude".into(), points);
        let policy = HistoryRetention::FileSize {
            bytes: point_bytes(&point(days_before(now, 1), 20.0)),
        };
        let preview = history.preview_prune(&policy, now);
        assert_eq!(preview.removed_count, 2);
        assert_eq!(preview.removed_bytes, Some(removed_expected));
        let mut applied = history.clone();
        applied.prune(&policy, now);
        assert_eq!(applied.accounts["claude"].len(), 1);
        assert_eq!(applied.accounts["claude"][0].windows[0].1, 20.0);
    }

    // ---- Loosening / forever cleans nothing ---------------------------------

    #[test]
    fn forever_and_looser_bounds_remove_nothing() {
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.accounts.insert(
            "claude".into(),
            vec![point(days_before(now, 400), 10.0), point(now, 20.0)],
        );

        for policy in [
            HistoryRetention::Forever,
            HistoryRetention::Age {
                unit: AgeUnit::Years,
                amount: 5,
            },
            HistoryRetention::FileSize {
                bytes: u64::MAX / 2,
            },
        ] {
            let preview = history.preview_prune(&policy, now);
            assert_eq!(preview.removed_count, 0, "{policy:?} must remove nothing");
            assert_eq!(preview.newest_removed, None);
            assert_eq!(preview.oldest_kept, Some(days_before(now, 400)));
            let mut applied = history.clone();
            applied.prune(&policy, now);
            assert_eq!(applied, history, "{policy:?} must not mutate the store");
        }
    }

    /// An empty history previews an empty clean for every policy.
    #[test]
    fn an_empty_history_previews_nothing() {
        let now = Utc::now();
        let history = UsageHistory::default();
        for policy in [
            HistoryRetention::Forever,
            HistoryRetention::Age {
                unit: AgeUnit::Days,
                amount: 7,
            },
            HistoryRetention::FileSize { bytes: 0 },
        ] {
            let preview = history.preview_prune(&policy, now);
            assert_eq!(
                preview,
                PrunePreview {
                    removed_count: 0,
                    removed_bytes: matches!(policy, HistoryRetention::FileSize { .. }).then_some(0),
                    oldest_kept: None,
                    newest_removed: None,
                }
            );
        }
    }

    // ---- Corruption policy --------------------------------------------------

    /// A file we cannot parse is renamed aside — never deleted, never
    /// recovered — and the history starts fresh; a save still succeeds.
    #[test]
    fn a_corrupt_history_is_renamed_aside_and_starts_fresh() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(FILE_NAME), "{ this is not json").unwrap();

        let history = UsageHistory::load(dir.path());
        assert_eq!(history, UsageHistory::default());
        assert!(
            !dir.path().join(FILE_NAME).exists(),
            "the unreadable file must not stay in the store's path"
        );
        let kept = dir.path().join(format!("{FILE_NAME}.corrupt"));
        assert_eq!(
            std::fs::read_to_string(&kept).unwrap(),
            "{ this is not json",
            "the original bytes are kept aside, not deleted"
        );

        // A save still succeeds — the fault never blocks recording.
        let mut history = UsageHistory::default();
        history.record(&outcome(vec![ok("claude", 42.0)]), Utc::now());
        history.save(dir.path()).unwrap();
        assert_eq!(UsageHistory::load(dir.path()), history);
    }

    /// A file that exists but cannot be *read* follows the same policy as one
    /// that cannot be parsed.
    #[test]
    fn an_unreadable_history_is_treated_as_corrupt() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(FILE_NAME);
        std::fs::write(&path, b"readable bytes").unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o000)).unwrap();
            // As root (as some CI containers run), permission bits are advisory;
            // only assert the policy when the read actually fails.
            if std::fs::read(&path).is_err() {
                let history = UsageHistory::load(dir.path());
                assert_eq!(history, UsageHistory::default());
                assert!(!path.exists());
                assert!(dir.path().join(format!("{FILE_NAME}.corrupt")).exists());
            }
        }
    }

    /// A second corruption must not overwrite the first kept copy — the kept
    /// bytes are the only surviving record of what was there.
    #[test]
    fn a_second_corruption_keeps_the_earlier_copy() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(FILE_NAME), "first corrupt").unwrap();
        let _ = UsageHistory::load(dir.path());
        std::fs::write(dir.path().join(FILE_NAME), "second corrupt").unwrap();
        let _ = UsageHistory::load(dir.path());

        assert_eq!(
            std::fs::read_to_string(dir.path().join(format!("{FILE_NAME}.corrupt"))).unwrap(),
            "first corrupt",
        );
        assert_eq!(
            std::fs::read_to_string(dir.path().join(format!("{FILE_NAME}.corrupt.2"))).unwrap(),
            "second corrupt",
        );
    }

    /// A missing file is the empty history, and loading it touches nothing —
    /// no directory created, no empty file written.
    #[test]
    fn a_missing_file_is_the_empty_history_and_creates_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let history = UsageHistory::load(dir.path());
        assert_eq!(history, UsageHistory::default());
        assert!(!dir.path().join(FILE_NAME).exists());
    }

    // ---- Persistence --------------------------------------------------------

    #[test]
    fn round_trips_through_disk() {
        let dir = tempfile::tempdir().unwrap();
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.record(
            &outcome(vec![ok("claude", 42.0), ok_credits("openrouter", 3.42)]),
            now,
        );
        history.save(dir.path()).unwrap();
        assert_eq!(UsageHistory::load(dir.path()), history);
    }

    /// `version` plus `#[serde(default)]` tolerate an older and a newer file:
    /// missing fields fall back to their defaults, and unknown fields from a
    /// newer build are ignored rather than fatal.
    #[test]
    fn an_older_or_newer_version_is_tolerated() {
        let dir = tempfile::tempdir().unwrap();
        // An older file: version but no accounts field.
        std::fs::write(dir.path().join(FILE_NAME), r#"{ "version": 1 }"#).unwrap();
        assert_eq!(UsageHistory::load(dir.path()), UsageHistory::default());

        // A newer file: a version this build has never seen, plus a field it
        // does not know. The points still load.
        let now = Utc::now();
        std::fs::write(
            dir.path().join(FILE_NAME),
            format!(
                r#"{{ "version": 999, "future_field": true, "accounts": {{ "claude": [
                    {{ "at": {}, "windows": [["five_hour", 42.0]], "credits_balance": null, "failed": false }}
                ] }} }}"#,
                serde_json::to_string(&now).unwrap(),
            ),
        )
        .unwrap();
        let loaded = UsageHistory::load(dir.path());
        assert_eq!(loaded.accounts["claude"].len(), 1);
        assert_eq!(loaded.accounts["claude"][0].windows[0].1, 42.0);
    }

    // ---- The host seams: capture and apply_policy ---------------------------

    /// `capture` is the whole host responsibility in one call: under the store
    /// lock, an unchanged re-capture adds nothing, and the active policy is
    /// applied to the store as part of recording.
    #[test]
    fn capture_records_coalesced_and_applies_the_active_policy() {
        let dir = tempfile::tempdir().unwrap();
        let now = Utc::now();
        let policy = HistoryRetention::Age {
            unit: AgeUnit::Days,
            amount: 7,
        };

        UsageHistory::capture(dir.path(), &outcome(vec![ok("claude", 42.0)]), &policy, now)
            .unwrap();
        // An unchanged observation: the store does not grow.
        UsageHistory::capture(
            dir.path(),
            &outcome(vec![ok("claude", 42.2)]),
            &policy,
            now + chrono::Duration::seconds(60),
        )
        .unwrap();
        let history = UsageHistory::load(dir.path());
        assert_eq!(history.accounts["claude"].len(), 1);

        // A changed observation records — and pre-seeded points older than
        // the policy are cleaned in the same pass.
        let mut old = UsageHistory::default();
        old.accounts
            .insert("claude".into(), vec![point(days_before(now, 30), 1.0)]);
        old.save(dir.path()).unwrap();
        UsageHistory::capture(
            dir.path(),
            &outcome(vec![ok("claude", 50.0)]),
            &policy,
            now + chrono::Duration::seconds(120),
        )
        .unwrap();
        let history = UsageHistory::load(dir.path());
        let points = &history.accounts["claude"];
        assert_eq!(
            points.len(),
            1,
            "the 30-day-old point fell outside the 7-day policy"
        );
        assert_eq!(points[0].windows[0].1, 50.0);
    }

    /// `apply_policy` prunes the stored history under the new policy and
    /// returns the same figures its preview showed — the confirm step of the
    /// cleaning-preview flow.
    #[test]
    fn apply_policy_cleans_and_returns_the_previewed_figures() {
        let dir = tempfile::tempdir().unwrap();
        let now = Utc::now();
        let mut history = UsageHistory::default();
        history.accounts.insert(
            "claude".into(),
            vec![
                point(days_before(now, 30), 10.0),
                point(days_before(now, 1), 20.0),
            ],
        );
        history.save(dir.path()).unwrap();

        let policy = HistoryRetention::Age {
            unit: AgeUnit::Days,
            amount: 7,
        };
        let expected = history.preview_prune(&policy, now);
        let applied = UsageHistory::apply_policy(dir.path(), &policy, now).unwrap();
        assert_eq!(applied, expected);
        assert_eq!(applied.removed_count, 1);

        let after = UsageHistory::load(dir.path());
        assert_eq!(after.accounts["claude"].len(), 1);
        assert_eq!(after.accounts["claude"][0].windows[0].1, 20.0);
    }
}
